// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmlxgczvrxkhurejqqod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbHhnY3p2cnhraHVyZWpxcW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODgyNTEsImV4cCI6MjA2NTE2NDI1MX0.dLeScWsevYyIDQQtIJaoHK2n2NsX96d26ernYKuWW0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);